# Generated by Django 4.2.6 on 2023-10-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sobrenome", models.CharField(max_length=200)),
                ("idade", models.IntegerField(default=0)),
                ("foto", models.ImageField(upload_to="foto-aluno")),
                (
                    "qrcode",
                    models.ImageField(blank=True, null=True, upload_to="qrcode"),
                ),
            ],
        ),
    ]
